#!/bin/bash

#PBS -S /bin/bash
#PBS -N merge
#PBS -o ro.txt
#PBS -j oe
#PBS -l walltime=04:00:00
#PBS -l select=2:ncpus=24:mpiprocs=24
#PBS -M filippo.gatti@centralesupelec.fr
#PBS -q haswellq
#PBS -P omaha

# chargement des modules ===========================================
module purge
module load intel-compilers/17.0.4
module load intel-mkl/11.3.3
module load intel-mpi/5.1.2
module load python/2.7.12
module load phdf5/1.8.17-IntelMPI-bis

cd $PBS_O_WORKDIR
mpirun -np 27 /home/gattif/nscarl/build/merge3dFields.exe < merge_het.txt
